[project]
name = "littlelemondjango"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "django==6.0.5",
    "django-cors-headers==4.9.0",
    "django-extensions==4.1",
    "djangorestframework==3.16.0",
    "djangorestframework-simplejwt==5.5.1",
    "djangorestframework-xml==2.0.0",
    "djoser==2.3.1",
    "fastmcp==3.3.1",
    "mcp==1.27.1",
    "numpy==2.2.6",
    "ollmcp==0.17.0",
    "pandas==2.2.3",
    "requests==2.34.2",
    "uvicorn==0.47.0",
]

[tool.uv]
exclude-newer = "7 days"
